### ISSUE TITLE
Can't build with ament

### ISSUE THREAD

**Issue by Theosakamg** [ros2-java/ros2_java_examples#1]
when i build the project with : `ament build --symlink-install --isolated --only-package rcljava_examples`

return output :

```
Process package 'rcljava_examples' with context:
--------------------------------------------------------------------------------
 source_space => /home/micky/ros-workspace/ros2java/ros2_java_ws/src/ros2_java/ros2_java_examples/rcljava_examples
  build_space => /home/micky/ros-workspace/ros2java/ros2_java_ws/build_isolated/rcljava_examples
install_space => /home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rcljava_examples
   make_flags => -j4, -l4
  build_tests => False
--------------------------------------------------------------------------------
+++ Building 'rcljava_examples'
Traceback (most recent call last):
  File "/home/micky/ros-workspace/ros2java/ament_ws/install_isolated/ament_tools/bin/ament", line 9, in <module>
    load_entry_point('ament-tools', 'console_scripts', 'ament')()
  File "/home/micky/ros-workspace/ros2java/ament_ws/build_isolated/ament_tools/ament_tools/commands/ament.py", line 88, in main
    rc = args.main(args)
  File "/home/micky/ros-workspace/ros2java/ament_ws/build_isolated/ament_tools/ament_tools/verbs/build/cli.py", line 164, in main
    return iterate_packages(opts, packages, per_package_main)
  File "/home/micky/ros-workspace/ros2java/ament_ws/build_isolated/ament_tools/ament_tools/verbs/build/cli.py", line 295, in iterate_packages
    rc = processSequentially(jobs)
  File "/home/micky/ros-workspace/ros2java/ament_ws/build_isolated/ament_tools/ament_tools/verbs/build/cli.py", line 335, in processSequentially
    rc = job['callback'](job['opts'])
  File "/home/micky/ros-workspace/ros2java/ament_ws/build_isolated/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 270, in main
    return run(opts, context)
  File "/home/micky/ros-workspace/ros2java/ament_ws/build_isolated/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 315, in run
    handle_build_action(on_build_ret, context)
  File "/home/micky/ros-workspace/ros2java/ament_ws/build_isolated/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 260, in handle_build_action
    run_command(build_action, context)
  File "/home/micky/ros-workspace/ros2java/ament_ws/build_isolated/ament_tools/ament_tools/verbs/build_pkg/cli.py", line 238, in run_command
    print("==> '{0}' in '{1}'".format(" ".join(build_action.cmd), cwd))
TypeError: sequence item 0: expected str instance, NoneType found
```

dump : 
content of **context**

```
install_space                      => /home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rcljava_examples
symlink_install                    => True
ament_gradle_args                  => []
source_space                       => /home/micky/ros-workspace/ros2java/ros2_java_ws/src/ros2_java/ros2_java_examples/rcljava_examples
make_flags                         => ['-j4', '-l4']
build_tests                        => False
exec_dependency_paths_in_workspace => ['/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_java/share/rosidl_generator_java', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/example_interfaces/share/example_interfaces', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rcljava/share/rcljava', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/std_msgs/share/std_msgs', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/sensor_msgs/share/sensor_msgs']
build_space                        => /home/micky/ros-workspace/ros2java/ros2_java_ws/build_isolated/rcljava_examples
install                            => True
dry_run                            => False
package_manifest                   => {'test_depends': [], 'buildtool_export_depends': [], 'name': 'rcljava_examples', 'build_export_depends': [], 'urls': [], 'exports': [<ament_package.export.Export object at 0x7f48b5e7a0c8>], 'filename': '/home/micky/ros-workspace/ros2java/ros2_java_ws/src/ros2_java/ros2_java_examples/rcljava_examples/package.xml', 'package_format': 2, 'buildtool_depends': [<ament_package.dependency.Dependency object at 0x7f48b5f0bf68>, <ament_package.dependency.Dependency object at 0x7f48b5f0bca8>, <ament_package.dependency.Dependency object at 0x7f48b5f0bc50>, <ament_package.dependency.Dependency object at 0x7f48b5f0b938>, <ament_package.dependency.Dependency object at 0x7f48b5f0b8e0>], 'build_depends': [<ament_package.dependency.Dependency object at 0x7f48b5f0d0f8>, <ament_package.dependency.Dependency object at 0x7f48b5f0d0a0>, <ament_package.dependency.Dependency object at 0x7f48b5f0b3b8>, <ament_package.dependency.Dependency object at 0x7f48b5f0bfc0>], 'maintainers': [<ament_package.person.Person object at 0x7f48b5f07588>], 'authors': [], 'replaces': [], 'doc_depends': [], 'licenses': ['Apache License 2.0'], 'exec_depends': [<ament_package.dependency.Dependency object at 0x7f48b5f0b9e8>, <ament_package.dependency.Dependency object at 0x7f48b5f0b990>, <ament_package.dependency.Dependency object at 0x7f48b5f0b728>, <ament_package.dependency.Dependency object at 0x7f48b5f0bf10>, <ament_package.dependency.Dependency object at 0x7f48b5f0b780>], 'conflicts': [], 'version': '0.0.0', 'description': 'Package containing examples of how to use the rcljava API.'}
build_dependencies                 => ['/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/ament_cmake_export_jars/share/ament_cmake_export_jars', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/connext_cmake_module/share/connext_cmake_module', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/fastcdr/share/fastcdr', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/fastrtps/share/fastrtps', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/opensplice_cmake_module/share/opensplice_cmake_module', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/python_cmake_module/share/python_cmake_module', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw/share/rmw', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_implementation_cmake/share/rmw_implementation_cmake', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_cmake/share/rosidl_cmake', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_default_generators/share/rosidl_default_generators', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_default_runtime/share/rosidl_default_runtime', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_dds_idl/share/rosidl_generator_dds_idl', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_parser/share/rosidl_parser', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_c/share/rosidl_generator_c', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_connext_shared_cpp/share/rmw_connext_shared_cpp', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_cpp/share/rosidl_generator_cpp', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_java/share/rosidl_generator_java', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_connext_cpp/share/rosidl_typesupport_connext_cpp', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_connext_c/share/rosidl_typesupport_connext_c', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_connext_cpp/share/rmw_connext_cpp', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_introspection_c/share/rosidl_typesupport_introspection_c', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_introspection_cpp/share/rosidl_typesupport_introspection_cpp', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_connext_dynamic_cpp/share/rmw_connext_dynamic_cpp', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_fastrtps_cpp/share/rmw_fastrtps_cpp', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_opensplice_cpp/share/rosidl_typesupport_opensplice_cpp', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_opensplice_c/share/rosidl_typesupport_opensplice_c', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_opensplice_cpp/share/rmw_opensplice_cpp', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_implementation/share/rmw_implementation', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_py/share/rosidl_generator_py', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/builtin_interfaces/share/builtin_interfaces', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/example_interfaces/share/example_interfaces', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rcl_interfaces/share/rcl_interfaces', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/std_msgs/share/std_msgs', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/geometry_msgs/share/geometry_msgs', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rcl/share/rcl', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rcljava/share/rcljava', '/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/sensor_msgs/share/sensor_msgs']
```

content of **build_action.cmd** 

```
[None, '-Pament.build_space=/home/micky/ros-workspace/ros2java/ros2_java_ws/build_isolated/rcljava_examples', '-Pament.install_space=/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rcljava_examples', '-Pament.dependencies=/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/ament_cmake_export_jars/share/ament_cmake_export_jars:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/connext_cmake_module/share/connext_cmake_module:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/fastcdr/share/fastcdr:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/fastrtps/share/fastrtps:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/opensplice_cmake_module/share/opensplice_cmake_module:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/python_cmake_module/share/python_cmake_module:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw/share/rmw:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_implementation_cmake/share/rmw_implementation_cmake:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_cmake/share/rosidl_cmake:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_default_generators/share/rosidl_default_generators:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_default_runtime/share/rosidl_default_runtime:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_dds_idl/share/rosidl_generator_dds_idl:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_parser/share/rosidl_parser:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_c/share/rosidl_generator_c:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_connext_shared_cpp/share/rmw_connext_shared_cpp:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_cpp/share/rosidl_generator_cpp:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_java/share/rosidl_generator_java:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_connext_cpp/share/rosidl_typesupport_connext_cpp:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_connext_c/share/rosidl_typesupport_connext_c:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_connext_cpp/share/rmw_connext_cpp:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_introspection_c/share/rosidl_typesupport_introspection_c:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_introspection_cpp/share/rosidl_typesupport_introspection_cpp:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_connext_dynamic_cpp/share/rmw_connext_dynamic_cpp:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_fastrtps_cpp/share/rmw_fastrtps_cpp:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_opensplice_cpp/share/rosidl_typesupport_opensplice_cpp:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_typesupport_opensplice_c/share/rosidl_typesupport_opensplice_c:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_opensplice_cpp/share/rmw_opensplice_cpp:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rmw_implementation/share/rmw_implementation:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rosidl_generator_py/share/rosidl_generator_py:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/builtin_interfaces/share/builtin_interfaces:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/example_interfaces/share/example_interfaces:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rcl_interfaces/share/rcl_interfaces:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/std_msgs/share/std_msgs:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/geometry_msgs/share/geometry_msgs:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rcl/share/rcl:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/rcljava/share/rcljava:/home/micky/ros-workspace/ros2java/ros2_java_ws/install_isolated/sensor_msgs/share/sensor_msgs', 'build']
```

**Comment by Theosakamg** [comment]
Solution need to install gradle on the system :
`aptitude install gradle`
